[[doing]]
title = "Data Mining & Deep Learning"
icon = "./config/assets/icons/analytics.svg"
# icon = "analytics"
text = "I am passionate about leveraging data mining and deep learning approaches to solve complex problems across various domains. My primary focus lies in applying these algorithms to time series data, gaining valuable insights from spatio-temporal patterns."

[[doing]]
title = "Computer Vision"
icon = "./config/assets/icons/aperture.svg"
# icon = "aperture"
text = "Working with images has always been one of my core interests, leading me to explore different computer vision tasks. I have completed several projects in areas such as Object Detection, Face Reconstruction, and Image Classification."

[[doing]]
title = "Trustworthy AI"
icon = "./config/assets/icons/lock-open.svg"
text = "I am passionate about Trustworthy AI because it addresses the real-world challenges of deep learning models. My interests include tackling problems like out-of-domain generalization, adversarial attacks and defenses, and anomaly detection, especially in vision models."

[[doing]]
title = "Human Computer Interaction"
icon = "./config/assets/icons/hand-left.svg"
# icon = "hand-right"
text = "In addition to the software side, I found working with microcontrollers and sensors to be incredibly fascinating. In my first academic paper, we developed an end-to-end approach to detect Persian Sign Language glosses. I believe this area holds immense potential for advancing human-computer interaction."
