[[project]]
title = "Football Tactical Pattern Recognition (FTPR)"
category = "Artificial Intelligence"
image = "./config/assets/projects/ftpr.png"
url = "https://github.com/amirparsa-Sal/Football-Tactical-Pattern-Recognition/"

[[project]]
title = "Persian Sign Language Recognition"
category = "Artificial Intelligence"
image = "./config/assets/projects/penslr2.png"
url = "https://github.com/persian-Sign-Language/PenSLR"

[[project]]
title = "Edge Detection Algorithms"
category = "Image Processing"
image = "./config/assets/projects/edge-detection.png"
url = "https://github.com/Amirparsa-Sal/Edge-Detection-Algorithms"

[[project]]
title = "Sign Language Time Series Clustering"
category = "Artificial Intelligence"
image = "./config/assets/projects/penslr-clustering.png"
url = "https://github.com/Amirparsa-Sal/Sign-Language-Glove-Time-Series-Clustering"

[[project]]
title = "Snail Jumper Evolution"
category = "Artificial Intelligence"
image = "./config/assets/projects/snail-jumper.png"
url = "https://github.com/Amirparsa-Sal/SnailJumper-Evolution"

[[project]]
title = "Digital Image Processing Projects"
category = "Image Processing"
image = "./config/assets/projects/brain.png"
url = "https://github.com/Amirparsa-Sal/Digital-Image-Processing/"

[[project]]
title = "CAPTCHA Solver"
category = "Artificial Intelligence"
image = "./config/assets/projects/captcha.png"
url = "https://github.com/Amirparsa-Sal/CAPTCHA-Solver"

[[project]]
title = "Heart Disease Fuzzy Expert System"
category = "Artificial Intelligence"
image = "./config/assets/projects/fuzzy2.png"
url = "https://github.com/Amirparsa-Sal/Heart-Disease-Fuzzy-Expert-System"

[[project]]
title = "CIFAR 10 Image Classification"
category = "Artificial Intelligence"
image = "./config/assets/projects/cifar10.png"
url = "https://github.com/Amirparsa-Sal/CIFAR10-Image-Classification"

[[project]]
title = "Arduino Projects"
category = "Hardware"
image = "./config/assets/projects/micro.png"
url = "https://github.com/Amirparsa-Sal/Micro-Processor-Assembly-Lab"

[[project]]
title = "Information Retreival Search Engine"
category = "Artificial Intelligence"
image = "./config/assets/projects/information-ret.png"
url = "https://github.com/Amirparsa-Sal/Information-Retrieval-Search-Engine"

[[project]]
title = "Telegram Teaching Assistant Bot"
category = "Web Development"
image = "./config/assets/projects/ta-bot.png"
url = "https://github.com/Amirparsa-Sal/TA-BOT"

[[project]]
title = "URL Shortener"
category = "Web Development"
image = "./config/assets/projects/url-shortener.png"
url = "https://github.com/Amirparsa-Sal/Url-Shortener"